version: '3'

services:
    golang:
        build: .
        ports:
            - "8080:8080"
        container_name: mohohewo
        depends_on:
            - mysql
    # mysql のサービスを追加
    mysql:
        image: mysql:5.7.22
        environment:
            MYSQL_ROOT_PASSWORD: golang
        container_name: mysql-container
